version: '3.0'
services:
  iotsignals:
    image: repo.secure.amsterdam.nl/datapunt/iotsignals:${ENVIRONMENT}
    environment:
      DATABASE_NAME: iotsignals
      DATABASE_USER: iotsignals
      DATABASE_PASSWORD:
      DATABASE_HOST:
      DATABASE_PORT:
